export const CATEGORY_REQUEST = 'CATEGORY_REQUEST'
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS'
export const CATEGORY_FAILURE = 'CATEGORY_FAILURE'
export const POST_CATEGORY_SUCCESS = 'POST_CATEGORY_SUCCESS'

